package com.example.smartcoach;

import android.content.Intent;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.example.smartcoach.models.AutoGeneratedWorkout;
import com.example.smartcoach.models.UserProfile;
import com.example.smartcoach.WorkoutListActivity;
import com.google.android.material.snackbar.Snackbar;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

public class GenerateWorkoutActivity extends AppCompatActivity {
    private FirebaseAuth auth;
    private DatabaseReference profilesDb;
    private DatabaseReference userWorkoutsDb;
    private Spinner fitnessGoalSpinner;
    private Spinner trainingModeSpinner;
    private TextView workoutResult;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_generate_workout);

        auth = FirebaseAuth.getInstance();
        profilesDb = FirebaseDatabase.getInstance().getReference("UserProfile");

        fitnessGoalSpinner = findViewById(R.id.fitnessGoalSpinner);
        trainingModeSpinner = findViewById(R.id.trainingModeSpinner);
        workoutResult = findViewById(R.id.workoutResult);
        Button generateButton = findViewById(R.id.generateButton);
        Button viewListButton = findViewById(R.id.btnViewList);

        // Настройка спиннеров
        ArrayAdapter<CharSequence> goalAdapter = ArrayAdapter.createFromResource(
                this, R.array.fitness_goals, android.R.layout.simple_spinner_item);
        goalAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        fitnessGoalSpinner.setAdapter(goalAdapter);

        ArrayAdapter<CharSequence> modeAdapter = ArrayAdapter.createFromResource(
                this, R.array.training_modes, android.R.layout.simple_spinner_item);
        modeAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        trainingModeSpinner.setAdapter(modeAdapter);

        generateButton.setOnClickListener(v -> generateWorkout());
        viewListButton.setOnClickListener(v -> {
            startActivity(new Intent(this, WorkoutListActivity.class));
        });
    }

    private void generateWorkout() {
        if (auth.getCurrentUser() == null) {
            Snackbar.make(findViewById(R.id.generateButton),
                    "Please log in first", Snackbar.LENGTH_SHORT).show();
            return;
        }

        String userId = auth.getCurrentUser().getUid();
        userWorkoutsDb = FirebaseDatabase.getInstance()
                .getReference("AutoGeneratedWorkouts")
                .child(userId);

        String fitnessGoal = fitnessGoalSpinner.getSelectedItem().toString();
        String trainingMode = trainingModeSpinner.getSelectedItem().toString();

        String profileId = profilesDb.push().getKey();
        UserProfile profile = new UserProfile(profileId, userId, fitnessGoal, trainingMode);
        profilesDb.child(userId).setValue(profile)
                .addOnFailureListener(e -> Snackbar.make(
                        findViewById(R.id.generateButton),
                        "Error saving profile: " + e.getMessage(),
                        Snackbar.LENGTH_LONG
                ).show());

        List<String> exercises = new ArrayList<>();
        switch (fitnessGoal) {
            case "Weight Loss":
                exercises.add("Running: 15 min");
                exercises.add("Jumping Jacks: 3 sets of 20");
                exercises.add("Bicycle Crunches: 3 sets of 15");
                break;
            case "Muscle Gain":
                exercises.add("Push-ups: 4 sets of 12");
                exercises.add("Squats: 4 sets of 10");
                exercises.add("Deadlifts: 3 sets of 8");
                break;
            default:
                exercises.add("Plank: 3 sets of 30 sec");
                exercises.add("Burpees: 3 sets of 10");
                exercises.add("Stretching: 10 min");
        }

        Collections.shuffle(exercises);
        String suggestedWorkout = String.join("\n", exercises.subList(0, 3));
        String intensityLevel = trainingMode.equals("Beginner") ? "Low"
                : trainingMode.equals("Intermediate") ? "Medium" : "High";
        int sets = trainingMode.equals("Beginner") ? 3 : 4;
        int duration = 45;
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String workoutId = userWorkoutsDb.push().getKey();

        AutoGeneratedWorkout workout = new AutoGeneratedWorkout(
                workoutId, userId, suggestedWorkout,
                duration, intensityLevel, sets, date, fitnessGoal
        );

        assert workoutId != null;
        userWorkoutsDb.child(workoutId)
                .setValue(workout)
                .addOnSuccessListener(aVoid -> {
                    workoutResult.setText("Generated Workout:\n" + suggestedWorkout);
                    Snackbar.make(findViewById(R.id.generateButton),
                            "Workout saved!", Snackbar.LENGTH_SHORT).show();
                })
                .addOnFailureListener(e -> Snackbar.make(
                        findViewById(R.id.generateButton),
                        "Error: " + e.getMessage(),
                        Snackbar.LENGTH_LONG
                ).show());
    }
}