package com.example.smartcoach;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;

import androidx.appcompat.app.AppCompatActivity;

import com.example.smartcoach.models.AutoGeneratedWorkout;
import com.google.android.material.snackbar.Snackbar;
import com.google.android.material.textfield.TextInputEditText;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.text.SimpleDateFormat;
import java.util.Date;

public class LoginActivity extends AppCompatActivity {

    private FirebaseAuth auth;
    private TextInputEditText emailInput, passwordInput;
    private View loginButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        auth = FirebaseAuth.getInstance();

        // Инициализация полей ввода
        emailInput = findViewById(R.id.emailInput);
        passwordInput = findViewById(R.id.passwordInput);
        loginButton = findViewById(R.id.loginButton);

        // Анимация для кнопки
        Animation scaleAnimation = AnimationUtils.loadAnimation(this, R.anim.button_scale);
        loginButton.startAnimation(scaleAnimation);

        // Обработчик нажатия на кнопку авторизации
        loginButton.setOnClickListener(v -> {
            String email = emailInput.getText().toString().trim();
            String password = passwordInput.getText().toString().trim();

            if (TextUtils.isEmpty(email)) {
                Snackbar.make(v, "Будь ласка, введіть email", Snackbar.LENGTH_SHORT).show();
                return;
            }
            if (TextUtils.isEmpty(password)) {
                Snackbar.make(v, "Будь ласка, введіть пароль", Snackbar.LENGTH_SHORT).show();
                return;
            }

            auth.signInWithEmailAndPassword(email, password)
                    .addOnSuccessListener(authResult -> {
                        Snackbar.make(v, "Авторизація успішна", Snackbar.LENGTH_SHORT).show();
                        // После успешной авторизации проверяем наличие тренировок
                        checkAndCreateDefaultWorkout(v);
                    })
                    .addOnFailureListener(e -> {
                        Snackbar.make(v, "Помилка авторизації: " + e.getMessage(), Snackbar.LENGTH_LONG).show();
                    });
        });

        // Обработчик нажатия на "Немає акаунта? Зареєструватися"
        findViewById(R.id.registerLink).setOnClickListener(v -> {
            Intent intent = new Intent(LoginActivity.this, RegisterActivity.class);
            startActivity(intent);
            overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
        });
    }

    private void checkAndCreateDefaultWorkout(View v) {
        String userId = auth.getCurrentUser().getUid();
        DatabaseReference ref = FirebaseDatabase.getInstance()
                .getReference("AutoGeneratedWorkouts")
                .child(userId);

        ref.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                if (!snapshot.exists() || snapshot.getChildrenCount() == 0) {
                    // Если тренировок нет, создаем дефолтную "Full Body" тренировку
                    proceedToHomeActivity();
                } else {
                    // Если тренировки есть, переходим на HomeActivity
                    proceedToHomeActivity();
                }
            }

            @Override
            public void onCancelled(DatabaseError error) {
                Log.e("LoginActivity", "Failed to check workouts: " + error.getMessage());
                Snackbar.make(v, "Помилка: " + error.getMessage(), Snackbar.LENGTH_LONG).show();
                proceedToHomeActivity(); // Переходим даже в случае ошибки
            }
        });
    }



    private void proceedToHomeActivity() {
        Intent intent = new Intent(LoginActivity.this, HomeActivity.class);
        startActivity(intent);
        overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
        finish();
    }
}