package com.example.smartcoach;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;

import androidx.appcompat.app.AppCompatActivity;

import com.example.smartcoach.models.AutoGeneratedWorkout;
import com.example.smartcoach.models.User;
import com.google.android.material.snackbar.Snackbar;
import com.google.android.material.textfield.TextInputEditText;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.text.SimpleDateFormat;
import java.util.Date;

public class RegisterActivity extends AppCompatActivity {

    private FirebaseAuth auth;
    private DatabaseReference users;
    private DatabaseReference userWorkoutsDb;
    private TextInputEditText emailInput, passwordInput, nameInput;
    private View registerButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register);

        // Инициализация FirebaseAuth и ссылки на базу данных
        auth = FirebaseAuth.getInstance();
        users = FirebaseDatabase.getInstance().getReference("Users");
        userWorkoutsDb = FirebaseDatabase.getInstance().getReference("AutoGeneratedWorkouts");

        // Инициализация полей ввода
        emailInput = findViewById(R.id.emailInput);
        passwordInput = findViewById(R.id.passwordInput);
        nameInput = findViewById(R.id.nameInput);
        registerButton = findViewById(R.id.registerButton);

        // Анимация для кнопки
        Animation scaleAnimation = AnimationUtils.loadAnimation(this, R.anim.button_scale);
        registerButton.startAnimation(scaleAnimation);

        // Обработчик нажатия на кнопку регистрации
        registerButton.setOnClickListener(v -> {
            String email = emailInput.getText().toString().trim();
            String password = passwordInput.getText().toString().trim();
            String name = nameInput.getText().toString().trim();

            // Проверка корректности введённых данных
            if (TextUtils.isEmpty(email)) {
                Snackbar.make(v, "Будь ласка, введіть email", Snackbar.LENGTH_SHORT).show();
                return;
            }
            if (TextUtils.isEmpty(name)) {
                Snackbar.make(v, "Будь ласка, введіть ім'я", Snackbar.LENGTH_SHORT).show();
                return;
            }
            if (password.length() < 5) {
                Snackbar.make(v, "Пароль повинен містити більше 5 символів", Snackbar.LENGTH_SHORT).show();
                return;
            }

            // Создание пользователя с email и паролем
            auth.createUserWithEmailAndPassword(email, password)
                    .addOnCompleteListener(task -> {
                        if (task.isSuccessful()) {
                            FirebaseUser firebaseUser = auth.getCurrentUser();
                            if (firebaseUser != null) {
                                User user = new User();
                                user.setName(name);
                                user.setEmail(email);

                                users.child(firebaseUser.getUid()).setValue(user)
                                        .addOnSuccessListener(aVoid -> {
                                            Snackbar.make(v, "Реєстрація пройшла успішно", Snackbar.LENGTH_SHORT).show();
                                            // После успешного сохранения пользователя создаем дефолтную тренировку
                                            createDefaultFullBodyWorkout(firebaseUser.getUid(), v);
                                        })
                                        .addOnFailureListener(e -> {
                                            Snackbar.make(v, "Помилка бази даних: " + e.getMessage(), Snackbar.LENGTH_LONG).show();
                                            // В случае ошибки все равно переходим на HomeActivity
                                            proceedToHomeActivity();
                                        });
                            } else {
                                Snackbar.make(v, "Користувач не знайдений, спробуйте ще раз", Snackbar.LENGTH_LONG).show();
                            }
                        } else {
                            Snackbar.make(v, "Помилка реєстрації: " + task.getException().getMessage(), Snackbar.LENGTH_LONG).show();
                        }
                    });
        });

        // Обработчик нажатия на "Вже є акаунт? Увійти"
        findViewById(R.id.loginLink).setOnClickListener(v -> {
            Intent intent = new Intent(RegisterActivity.this, LoginActivity.class);
            startActivity(intent);
            overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
        });
    }

    private void createDefaultFullBodyWorkout(String userId, View v) {
        // Создаем дефолтную тренировку "Full Body"
        String suggestedWorkout = "Push-ups: 3 sets of 10\nSquats: 3 sets of 12\nPlank: 3 sets of 30 sec";
        String intensityLevel = "Medium";
        int sets = 3;
        int duration = 45;
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String workoutId = userWorkoutsDb.child(userId).push().getKey();
        String fitnessGoal = "Maintenance";

        String defaultGroup = "Full Body";
        AutoGeneratedWorkout defaultWorkout = new AutoGeneratedWorkout(
                workoutId,
                userId,
                suggestedWorkout,
                duration,
                intensityLevel,
                sets,
                date,
                fitnessGoal,
                defaultGroup
        );

        // Сохраняем тренировку в Firebase
        userWorkoutsDb.child(userId).child(workoutId).setValue(defaultWorkout)
                .addOnSuccessListener(aVoid -> {
                    Log.d("RegisterActivity", "Default Full Body workout created");
                    Snackbar.make(v, "Додано тренування Full Body!", Snackbar.LENGTH_SHORT).show();
                    proceedToHomeActivity();
                })
                .addOnFailureListener(e -> {
                    Log.e("RegisterActivity", "Failed to create default workout: " + e.getMessage());
                    Snackbar.make(v, "Помилка створення тренування: " + e.getMessage(), Snackbar.LENGTH_LONG).show();
                    proceedToHomeActivity();
                });
    }

    private void proceedToHomeActivity() {
        Intent intent = new Intent(RegisterActivity.this, HomeActivity.class);
        startActivity(intent);
        overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
        finish();
    }
}