package com.example.smartcoach;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.smartcoach.models.AutoGeneratedWorkout;

import java.util.List;

public class WorkoutAdapter extends RecyclerView.Adapter<WorkoutAdapter.HomeWorkoutViewHolder> {

    public static final int VIEW_TYPE_HOME = 0; // Константа для сумісності

    private List<AutoGeneratedWorkout> workouts;
    private OnWorkoutClickListener clickListener;

    public interface OnWorkoutClickListener {
        void onWorkoutClick(AutoGeneratedWorkout workout);
    }

    public WorkoutAdapter(List<AutoGeneratedWorkout> workouts, OnWorkoutClickListener clickListener) {
        this.workouts = workouts;
        this.clickListener = clickListener;
    }

    @NonNull
    @Override
    public HomeWorkoutViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_workout_card, parent, false);
        return new HomeWorkoutViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull HomeWorkoutViewHolder holder, int position) {
        AutoGeneratedWorkout workout = workouts.get(position);

        // Берём group из модели
        String muscleGroup = workout.getMuscleGroup();
        if (muscleGroup == null || muscleGroup.isEmpty()) {
            // fallback — на случай старых записей
            muscleGroup = WorkoutUtils.determineMuscleGroup(workout.getSuggestedWorkout());
        }

        // Заголовок с датой
        holder.workoutTitle.setText("Тренування " + workout.getDate());

        // Описание: цель, группа и список упражнений (переведённый)
        String description = "Ціль: " + WorkoutUtils.translateWorkoutGoal(workout.getWorkoutGoal())
                + "\nГрупа: " + WorkoutUtils.translateMuscleGroup(muscleGroup)
                + "\n" + WorkoutUtils.translateSuggestedWorkout(workout.getSuggestedWorkout());
        holder.workoutDescription.setText(description);

        // Картинка по группе
        WorkoutUtils.setMuscleImage(holder.muscleImage, muscleGroup);

        // Клики остаются прежними
        holder.itemView.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
        holder.startButton.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
    }

    @Override
    public int getItemCount() {
        return workouts.size();
    }

    public static class HomeWorkoutViewHolder extends RecyclerView.ViewHolder {
        TextView workoutTitle, workoutDescription;
        ImageView muscleImage;
        Button startButton;

        public HomeWorkoutViewHolder(@NonNull View itemView) {
            super(itemView);
            workoutTitle = itemView.findViewById(R.id.workout_title);
            workoutDescription = itemView.findViewById(R.id.workout_description);
            muscleImage = itemView.findViewById(R.id.muscle_image);
            startButton = itemView.findViewById(R.id.start_workout_button);
        }
    }
}

//package com.example.smartcoach;
//
//import android.view.LayoutInflater;
//import android.view.View;
//import android.view.ViewGroup;
//import android.widget.Button;
//import android.widget.ImageView;
//import android.widget.TextView;
//
//import androidx.annotation.NonNull;
//import androidx.recyclerview.widget.RecyclerView;
//
//import com.example.smartcoach.models.AutoGeneratedWorkout;
//
//import java.util.List;
//
//public class WorkoutAdapter extends RecyclerView.Adapter<WorkoutAdapter.HomeWorkoutViewHolder> {
//
//    public static final int VIEW_TYPE_HOME = 0; // Додаємо константу назад
//
//    private List<AutoGeneratedWorkout> workouts;
//    private OnWorkoutClickListener clickListener;
//
//    public interface OnWorkoutClickListener {
//        void onWorkoutClick(AutoGeneratedWorkout workout);
//    }
//
//    public WorkoutAdapter(List<AutoGeneratedWorkout> workouts, OnWorkoutClickListener clickListener) {
//        this.workouts = workouts;
//        this.clickListener = clickListener;
//    }
//
//    @NonNull
//    @Override
//    public HomeWorkoutViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
//        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_workout_card, parent, false);
//        return new HomeWorkoutViewHolder(view);
//    }
//
//    @Override
//    public void onBindViewHolder(@NonNull HomeWorkoutViewHolder holder, int position) {
//        AutoGeneratedWorkout workout = workouts.get(position);
//
//        holder.workoutTitle.setText("Тренування " + workout.getDate());
//        holder.workoutDescription.setText("Ціль: " + translateWorkoutGoal(workout.getWorkoutGoal()) + "\n" + workout.getSuggestedWorkout());
//
//        String muscleGroup = determineMuscleGroup(workout.getSuggestedWorkout());
//        holder.setMuscleImage(muscleGroup);
//
//        holder.itemView.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
//        holder.startButton.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
//    }
//
//    @Override
//    public int getItemCount() {
//        return workouts.size();
//    }
//
//    public static class HomeWorkoutViewHolder extends RecyclerView.ViewHolder {
//        TextView workoutTitle, workoutDescription;
//        ImageView muscleImage;
//        Button startButton;
//
//        public HomeWorkoutViewHolder(@NonNull View itemView) {
//            super(itemView);
//            workoutTitle = itemView.findViewById(R.id.workout_title);
//            workoutDescription = itemView.findViewById(R.id.workout_description);
//            muscleImage = itemView.findViewById(R.id.muscle_image);
//            startButton = itemView.findViewById(R.id.start_workout_button);
//        }
//
//        public void setMuscleImage(String muscleGroup) {
//            switch (muscleGroup.toLowerCase()) {
//                case "chest":
//                    muscleImage.setImageResource(R.drawable.ic_chest);
//                    break;
//                case "back":
//                    muscleImage.setImageResource(R.drawable.ic_back);
//                    break;
//                case "arms":
//                    muscleImage.setImageResource(R.drawable.ic_arms);
//                    break;
//                case "legs":
//                    muscleImage.setImageResource(R.drawable.ic_legs);
//                    break;
//                case "abs":
//                    muscleImage.setImageResource(R.drawable.ic_abs);
//                    break;
//                case "shoulders":
//                    muscleImage.setImageResource(R.drawable.ic_shoulders);
//                    break;
//                default:
//                    muscleImage.setImageResource(R.drawable.ic_default_workout);
//                    break;
//            }
//        }
//    }
//
//    private String determineMuscleGroup(String suggestedWorkout) {
//        if (suggestedWorkout.toLowerCase().contains("push-ups") || suggestedWorkout.toLowerCase().contains("bench press")) {
//            return "Chest";
//        } else if (suggestedWorkout.toLowerCase().contains("pull-ups") || suggestedWorkout.toLowerCase().contains("deadlifts")) {
//            return "Back";
//        } else if (suggestedWorkout.toLowerCase().contains("bicep curls") || suggestedWorkout.toLowerCase().contains("tricep dips")) {
//            return "Arms";
//        } else if (suggestedWorkout.toLowerCase().contains("squats") || suggestedWorkout.toLowerCase().contains("lunges")) {
//            return "Legs";
//        } else if (suggestedWorkout.toLowerCase().contains("plank") || suggestedWorkout.toLowerCase().contains("crunches")) {
//            return "Abs";
//        } else if (suggestedWorkout.toLowerCase().contains("shoulder press") || suggestedWorkout.toLowerCase().contains("lateral raises")) {
//            return "Shoulders";
//        } else {
//            return "Full Body";
//        }
//    }
//
//    private String translateWorkoutGoal(String goal) {
//        switch (goal.toLowerCase()) {
//            case "weight loss":
//                return "Схуднення";
//            case "muscle gain":
//                return "Набір м’язової маси";
//            case "maintain shape":
//                return "Підтримка форми";
//            default:
//                return goal;
//        }
//    }
//}

//package com.example.smartcoach;
//
//import android.view.LayoutInflater;
//import android.view.View;
//import android.view.ViewGroup;
//import android.widget.Button;
//import android.widget.ImageView;
//import android.widget.TextView;
//
//import androidx.annotation.NonNull;
//import androidx.recyclerview.widget.RecyclerView;
//
//import com.example.smartcoach.models.AutoGeneratedWorkout;
//
//import java.util.List;
//
//public class WorkoutAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
//    public static final int VIEW_TYPE_HOME = 0;
//    public static final int VIEW_TYPE_LIST = 1;
//
//    private List<AutoGeneratedWorkout> workouts;
//    private OnWorkoutClickListener clickListener;
//    private int viewType; // Тип відображення (для Home або List)
//
//    public interface OnWorkoutClickListener {
//        void onWorkoutClick(AutoGeneratedWorkout workout);
//    }
//
//    // Конструктор без clickListener (для WorkoutListActivity)
//    public WorkoutAdapter(List<AutoGeneratedWorkout> workouts, int viewType) {
//        this.workouts = workouts;
//        this.viewType = viewType;
//    }
//
//    // Конструктор з clickListener (для HomeActivity)
//    public WorkoutAdapter(List<AutoGeneratedWorkout> workouts, OnWorkoutClickListener clickListener, int viewType) {
//        this.workouts = workouts;
//        this.clickListener = clickListener;
//        this.viewType = viewType;
//    }
//
//    @Override
//    public int getItemViewType(int position) {
//        return viewType; // Повертаємо тип залежно від активності
//    }
//
//    @NonNull
//    @Override
//    public RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
//        if (viewType == VIEW_TYPE_HOME) {
//            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_workout_card, parent, false);
//            return new HomeWorkoutViewHolder(view);
//        } else {
//            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_workout, parent, false);
//            return new ListWorkoutViewHolder(view);
//        }
//    }
//
//    @Override
//    public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
//        AutoGeneratedWorkout workout = workouts.get(position);
//
//        if (holder instanceof HomeWorkoutViewHolder) {
//            HomeWorkoutViewHolder homeHolder = (HomeWorkoutViewHolder) holder;
//            // Установка заголовка і опису для HomeActivity
//            homeHolder.workoutTitle.setText("Тренування " + workout.getDate());
//            homeHolder.workoutDescription.setText("Ціль: " + translateWorkoutGoal(workout.getWorkoutGoal()) + "\n" + workout.getSuggestedWorkout());
//
//            // Визначення групи м’язів
//            String muscleGroup = determineMuscleGroup(workout.getSuggestedWorkout());
//            homeHolder.setMuscleImage(muscleGroup);
//
//            // Налаштування натискання на картку
//            homeHolder.itemView.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
//            homeHolder.startButton.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
//        } else if (holder instanceof ListWorkoutViewHolder) {
//            ListWorkoutViewHolder listHolder = (ListWorkoutViewHolder) holder;
//            // Установка даних для WorkoutListActivity
//            listHolder.dateText.setText(workout.getDate());
//            listHolder.goalText.setText("Ціль: " + translateWorkoutGoal(workout.getWorkoutGoal()));
//
//            // Визначення групи м’язів і установка назви та зображення
//            String muscleGroup = determineMuscleGroup(workout.getSuggestedWorkout());
//            listHolder.muscleGroupText.setText(translateMuscleGroup(muscleGroup));
//            listHolder.setMuscleImage(muscleGroup);
//
//            // Налаштування натискання на картку
//            listHolder.itemView.setOnClickListener(v -> clickListener.onWorkoutClick(workout));
//        }
//    }
//
//    @Override
//    public int getItemCount() {
//        return workouts.size();
//    }
//
//    // ViewHolder для HomeActivity (item_workout_card.xml)
//    public static class HomeWorkoutViewHolder extends RecyclerView.ViewHolder {
//        TextView workoutTitle, workoutDescription;
//        ImageView muscleImage;
//        Button startButton;
//
//        public HomeWorkoutViewHolder(@NonNull View itemView) {
//            super(itemView);
//            workoutTitle = itemView.findViewById(R.id.workout_title);
//            workoutDescription = itemView.findViewById(R.id.workout_description);
//            muscleImage = itemView.findViewById(R.id.muscle_image);
//            startButton = itemView.findViewById(R.id.start_workout_button);
//        }
//
//        public void setMuscleImage(String muscleGroup) {
//            switch (muscleGroup.toLowerCase()) {
//                case "chest":
//                    muscleImage.setImageResource(R.drawable.ic_chest);
//                    break;
//                case "back":
//                    muscleImage.setImageResource(R.drawable.ic_back);
//                    break;
//                case "arms":
//                    muscleImage.setImageResource(R.drawable.ic_arms);
//                    break;
//                case "legs":
//                    muscleImage.setImageResource(R.drawable.ic_legs);
//                    break;
//                case "abs":
//                    muscleImage.setImageResource(R.drawable.ic_abs);
//                    break;
//                case "shoulders":
//                    muscleImage.setImageResource(R.drawable.ic_shoulders);
//                    break;
//                default:
//                    muscleImage.setImageResource(R.drawable.ic_default_workout);
//                    break;
//            }
//        }
//    }
//
//    // ViewHolder для WorkoutListActivity (item_workout.xml)
//    public static class ListWorkoutViewHolder extends RecyclerView.ViewHolder {
//        TextView muscleGroupText, dateText, goalText;
//        ImageView muscleImage;
//
//        public ListWorkoutViewHolder(@NonNull View itemView) {
//            super(itemView);
//            muscleGroupText = itemView.findViewById(R.id.muscleGroupText);
//            dateText = itemView.findViewById(R.id.dateText);
//            goalText = itemView.findViewById(R.id.goalText);
//            muscleImage = itemView.findViewById(R.id.muscleImage);
//        }
//
//        public void setMuscleImage(String muscleGroup) {
//            switch (muscleGroup.toLowerCase()) {
//                case "chest":
//                    muscleImage.setImageResource(R.drawable.ic_chest);
//                    break;
//                case "back":
//                    muscleImage.setImageResource(R.drawable.ic_back);
//                    break;
//                case "arms":
//                    muscleImage.setImageResource(R.drawable.ic_arms);
//                    break;
//                case "legs":
//                    muscleImage.setImageResource(R.drawable.ic_legs);
//                    break;
//                case "abs":
//                    muscleImage.setImageResource(R.drawable.ic_abs);
//                    break;
//                case "shoulders":
//                    muscleImage.setImageResource(R.drawable.ic_shoulders);
//                    break;
//                default:
//                    muscleImage.setImageResource(R.drawable.ic_default_workout);
//                    break;
//            }
//        }
//    }
//
//    private String determineMuscleGroup(String suggestedWorkout) {
//        if (suggestedWorkout.toLowerCase().contains("push-ups") || suggestedWorkout.toLowerCase().contains("bench press")) {
//            return "Chest";
//        } else if (suggestedWorkout.toLowerCase().contains("pull-ups") || suggestedWorkout.toLowerCase().contains("deadlifts")) {
//            return "Back";
//        } else if (suggestedWorkout.toLowerCase().contains("bicep curls") || suggestedWorkout.toLowerCase().contains("tricep dips")) {
//            return "Arms";
//        } else if (suggestedWorkout.toLowerCase().contains("squats") || suggestedWorkout.toLowerCase().contains("lunges")) {
//            return "Legs";
//        } else if (suggestedWorkout.toLowerCase().contains("plank") || suggestedWorkout.toLowerCase().contains("crunches")) {
//            return "Abs";
//        } else if (suggestedWorkout.toLowerCase().contains("shoulder press") || suggestedWorkout.toLowerCase().contains("lateral raises")) {
//            return "Shoulders";
//        } else {
//            return "Full Body";
//        }
//    }
//
//    private String translateMuscleGroup(String muscleGroup) {
//        switch (muscleGroup.toLowerCase()) {
//            case "chest":
//                return "Груди";
//            case "back":
//                return "Спина";
//            case "arms":
//                return "Руки";
//            case "legs":
//                return "Ноги";
//            case "abs":
//                return "Прес";
//            case "shoulders":
//                return "Плечі";
//            case "full body":
//                return "Все тіло";
//            default:
//                return muscleGroup;
//        }
//    }
//
//    private String translateWorkoutGoal(String goal) {
//        switch (goal.toLowerCase()) {
//            case "weight loss":
//                return "Схуднення";
//            case "muscle gain":
//                return "Набір м’язової маси";
//            case "maintain shape":
//                return "Підтримка форми";
//            default:
//                return goal;
//        }
//    }
//}
