package com.example.smartcoach;

import android.content.Intent;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.example.smartcoach.models.AutoGeneratedWorkout;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class WorkoutDetailActivity extends AppCompatActivity {

    private TextView tvDetailDate, tvDetailGoal, tvDetailSuggested, tvDetailIntensity, tvDetailSets, tvDetailDuration;
    private ImageView muscleImage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_workout_detail);

        // Ініціалізація UI
        tvDetailDate = findViewById(R.id.tvDetailDate);
        tvDetailGoal = findViewById(R.id.tvDetailGoal);
        tvDetailSuggested = findViewById(R.id.tvDetailSuggested);
        tvDetailIntensity = findViewById(R.id.tvDetailIntensity);
        tvDetailSets = findViewById(R.id.tvDetailSets);
        tvDetailDuration = findViewById(R.id.tvDetailDuration);
        muscleImage = findViewById(R.id.muscle_image);

        // Отримання даних з Intent
        String workoutId = getIntent().getStringExtra("WORKOUT_ID");
        String userId = getIntent().getStringExtra("USER_ID");

        if (workoutId == null || userId == null) {
            finish();
            return;
        }

        // Завантаження даних тренування з Firebase
        loadWorkoutDetails(userId, workoutId);

        // Налаштування Bottom Navigation
        BottomNavigationView bottomNavigationView = findViewById(R.id.bottom_navigation);
        bottomNavigationView.setSelectedItemId(R.id.nav_generate_workout);
        bottomNavigationView.setOnNavigationItemSelectedListener(item -> {
            int itemId = item.getItemId();
            if (itemId == R.id.nav_home) {
                startActivity(new Intent(WorkoutDetailActivity.this, HomeActivity.class));
                finish();
                return true;
            } else if (itemId == R.id.nav_generate_workout) {
                startActivity(new Intent(WorkoutDetailActivity.this, GenerateWorkoutActivity.class));
                finish();
                return true;
            } else if (itemId == R.id.nav_settings) {
                startActivity(new Intent(WorkoutDetailActivity.this, SettingsActivity.class));
                finish();
                return true;
            }
            return false;
        });
    }

    private void loadWorkoutDetails(String userId, String workoutId) {
        DatabaseReference ref = FirebaseDatabase.getInstance()
                .getReference("AutoGeneratedWorkouts")
                .child(userId)
                .child(workoutId);

        ref.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                AutoGeneratedWorkout workout = snapshot.getValue(AutoGeneratedWorkout.class);
                if (workout != null) {
                    // Установка даних в UI
                    tvDetailDate.setText(workout.getDate());
                    tvDetailGoal.setText("Ціль: " + translateWorkoutGoal(workout.getWorkoutGoal()));
                    tvDetailSuggested.setText(translateSuggestedWorkout(workout.getSuggestedWorkout()));
                    tvDetailIntensity.setText(translateIntensityLevel(workout.getIntensityLevel()));
                    tvDetailSets.setText(String.valueOf(workout.getSets()));
                    tvDetailDuration.setText(String.valueOf(workout.getDuration()));

                    // Установка зображення групи м’язів
                    String muscleGroup = determineMuscleGroup(workout.getSuggestedWorkout());
                    setMuscleImage(muscleGroup);
                } else {
                    finish();
                }
            }

            @Override
            public void onCancelled(DatabaseError error) {
                finish();
            }
        });
    }

    private String determineMuscleGroup(String suggestedWorkout) {
        if (suggestedWorkout.toLowerCase().contains("push-ups") || suggestedWorkout.toLowerCase().contains("bench press")) {
            return "Chest";
        } else if (suggestedWorkout.toLowerCase().contains("pull-ups") || suggestedWorkout.toLowerCase().contains("deadlifts")) {
            return "Back";
        } else if (suggestedWorkout.toLowerCase().contains("bicep curls") || suggestedWorkout.toLowerCase().contains("tricep dips")) {
            return "Arms";
        } else if (suggestedWorkout.toLowerCase().contains("squats") || suggestedWorkout.toLowerCase().contains("lunges")) {
            return "Legs";
        } else if (suggestedWorkout.toLowerCase().contains("plank") || suggestedWorkout.toLowerCase().contains("crunches")) {
            return "Abs";
        } else if (suggestedWorkout.toLowerCase().contains("shoulder press") || suggestedWorkout.toLowerCase().contains("lateral raises")) {
            return "Shoulders";
        } else {
            return "Full Body";
        }
    }

    private void setMuscleImage(String muscleGroup) {
        switch (muscleGroup.toLowerCase()) {
            case "chest":
                muscleImage.setImageResource(R.drawable.ic_chest);
                break;
            case "back":
                muscleImage.setImageResource(R.drawable.ic_back);
                break;
            case "arms":
                muscleImage.setImageResource(R.drawable.ic_arms);
                break;
            case "legs":
                muscleImage.setImageResource(R.drawable.ic_legs);
                break;
            case "abs":
                muscleImage.setImageResource(R.drawable.ic_abs);
                break;
            case "shoulders":
                muscleImage.setImageResource(R.drawable.ic_shoulders);
                break;
            default:
                muscleImage.setImageResource(R.drawable.ic_default_workout);
                break;
        }
    }

    private String translateWorkoutGoal(String goal) {
        switch (goal.toLowerCase()) {
            case "weight loss":
                return "Схуднення";
            case "muscle gain":
                return "Набір м’язової маси";
            case "maintain shape":
                return "Підтримка форми";
            default:
                return goal;
        }
    }

    private String translateIntensityLevel(String intensity) {
        switch (intensity.toLowerCase()) {
            case "low":
                return "Низька";
            case "medium":
                return "Середня";
            case "high":
                return "Висока";
            default:
                return intensity;
        }
    }

    private String translateSuggestedWorkout(String suggestedWorkout) {
        StringBuilder translatedWorkout = new StringBuilder();
        String[] exercises = suggestedWorkout.split("\n");
        for (String exercise : exercises) {
            if (exercise.contains("Push-ups")) {
                translatedWorkout.append(exercise.replace("Push-ups", "Віджимання")).append("\n");
            } else if (exercise.contains("Bench Press")) {
                translatedWorkout.append(exercise.replace("Bench Press", "Жим лежачи")).append("\n");
            } else if (exercise.contains("Dumbbell Flyes")) {
                translatedWorkout.append(exercise.replace("Dumbbell Flyes", "Розведення гантелей")).append("\n");
            } else if (exercise.contains("Pull-ups")) {
                translatedWorkout.append(exercise.replace("Pull-ups", "Підтягування")).append("\n");
            } else if (exercise.contains("Deadlifts")) {
                translatedWorkout.append(exercise.replace("Deadlifts", "Станова тяга")).append("\n");
            } else if (exercise.contains("Bent-over Rows")) {
                translatedWorkout.append(exercise.replace("Bent-over Rows", "Тяга штанги в нахилі")).append("\n");
            } else if (exercise.contains("Bicep Curls")) {
                translatedWorkout.append(exercise.replace("Bicep Curls", "Згинання рук з гантелями")).append("\n");
            } else if (exercise.contains("Tricep Dips")) {
                translatedWorkout.append(exercise.replace("Tricep Dips", "Віджимання на трицепс")).append("\n");
            } else if (exercise.contains("Hammer Curls")) {
                translatedWorkout.append(exercise.replace("Hammer Curls", "Молоткові згинання")).append("\n");
            } else if (exercise.contains("Squats")) {
                translatedWorkout.append(exercise.replace("Squats", "Присідання")).append("\n");
            } else if (exercise.contains("Lunges")) {
                translatedWorkout.append(exercise.replace("Lunges", "Випади")).append("\n");
            } else if (exercise.contains("Leg Press")) {
                translatedWorkout.append(exercise.replace("Leg Press", "Жим ногами")).append("\n");
            } else if (exercise.contains("Plank")) {
                translatedWorkout.append(exercise.replace("Plank", "Планка")).append("\n");
            } else if (exercise.contains("Bicycle Crunches")) {
                translatedWorkout.append(exercise.replace("Bicycle Crunches", "Скручування «велосипед»")).append("\n");
            } else if (exercise.contains("Leg Raises")) {
                translatedWorkout.append(exercise.replace("Leg Raises", "Підйом ніг")).append("\n");
            } else if (exercise.contains("Shoulder Press")) {
                translatedWorkout.append(exercise.replace("Shoulder Press", "Жим плечима")).append("\n");
            } else if (exercise.contains("Lateral Raises")) {
                translatedWorkout.append(exercise.replace("Lateral Raises", "Бокові підйоми гантелей")).append("\n");
            } else if (exercise.contains("Front Raises")) {
                translatedWorkout.append(exercise.replace("Front Raises", "Фронтальні підйоми гантелей")).append("\n");
            } else if (exercise.contains("Running")) {
                translatedWorkout.append(exercise.replace("Running", "Біг")).append("\n");
            } else if (exercise.contains("Jumping Jacks")) {
                translatedWorkout.append(exercise.replace("Jumping Jacks", "Стрибки «Джек»")).append("\n");
            } else if (exercise.contains("Burpees")) {
                translatedWorkout.append(exercise.replace("Burpees", "Берпі")).append("\n");
            } else if (exercise.contains("Stretching")) {
                translatedWorkout.append(exercise.replace("Stretching", "Розтяжка")).append("\n");
            } else {
                translatedWorkout.append(exercise).append("\n");
            }
        }
        return translatedWorkout.toString().trim();
    }
}


//package com.example.smartcoach;
//
//import android.content.Intent;
//import android.os.Bundle;
//import android.widget.ImageView;
//import android.widget.TextView;
//
//import androidx.appcompat.app.AppCompatActivity;
//
//import com.example.smartcoach.models.AutoGeneratedWorkout;
//import com.google.android.material.bottomnavigation.BottomNavigationView;
//import com.google.firebase.database.DataSnapshot;
//import com.google.firebase.database.DatabaseError;
//import com.google.firebase.database.DatabaseReference;
//import com.google.firebase.database.FirebaseDatabase;
//import com.google.firebase.database.ValueEventListener;
//
//public class WorkoutDetailActivity extends AppCompatActivity {
//
//    private TextView tvDetailDate, tvDetailGoal, tvDetailSuggested, tvDetailIntensity, tvDetailSets, tvDetailDuration;
//    private ImageView muscleImage;
//
//    @Override
//    protected void onCreate(Bundle savedInstanceState) {
//        super.onCreate(savedInstanceState);
//        setContentView(R.layout.activity_workout_detail);
//
//        // Инициализация UI
//        tvDetailDate = findViewById(R.id.tvDetailDate);
//        tvDetailGoal = findViewById(R.id.tvDetailGoal);
//        tvDetailSuggested = findViewById(R.id.tvDetailSuggested);
//        tvDetailIntensity = findViewById(R.id.tvDetailIntensity);
//        tvDetailSets = findViewById(R.id.tvDetailSets);
//        tvDetailDuration = findViewById(R.id.tvDetailDuration);
//        muscleImage = findViewById(R.id.muscle_image);
//
//        // Получение данных из Intent
//        String workoutId = getIntent().getStringExtra("WORKOUT_ID");
//        String userId = getIntent().getStringExtra("USER_ID");
//
//        if (workoutId == null || userId == null) {
//            finish();
//            return;
//        }
//
//        // Загрузка данных тренировки из Firebase
//        loadWorkoutDetails(userId, workoutId);
//
//        // Настройка Bottom Navigation
//        BottomNavigationView bottomNavigationView = findViewById(R.id.bottom_navigation);
//        bottomNavigationView.setSelectedItemId(R.id.nav_generate_workout);
//        bottomNavigationView.setOnNavigationItemSelectedListener(item -> {
//            int itemId = item.getItemId();
//            if (itemId == R.id.nav_home) {
//                startActivity(new Intent(WorkoutDetailActivity.this, HomeActivity.class));
//                finish();
//                return true;
//            } else if (itemId == R.id.nav_generate_workout) {
//                startActivity(new Intent(WorkoutDetailActivity.this, GenerateWorkoutActivity.class));
//                finish();
//                return true;
//            } else if (itemId == R.id.nav_settings) {
//                startActivity(new Intent(WorkoutDetailActivity.this, SettingsActivity.class));
//                finish();
//                return true;
//            }
//            return false;
//        });
//    }
//
//    private void loadWorkoutDetails(String userId, String workoutId) {
//        DatabaseReference ref = FirebaseDatabase.getInstance()
//                .getReference("AutoGeneratedWorkouts")
//                .child(userId)
//                .child(workoutId);
//
//        ref.addListenerForSingleValueEvent(new ValueEventListener() {
//            @Override
//            public void onDataChange(DataSnapshot snapshot) {
//                AutoGeneratedWorkout workout = snapshot.getValue(AutoGeneratedWorkout.class);
//                if (workout != null) {
//                    // Установка данных в UI
//                    tvDetailDate.setText(workout.getDate());
//                    tvDetailGoal.setText("Goal: " + workout.getWorkoutGoal());
//                    tvDetailSuggested.setText(workout.getSuggestedWorkout());
//                    tvDetailIntensity.setText(workout.getIntensityLevel());
//                    tvDetailSets.setText(String.valueOf(workout.getSets()));
//                    tvDetailDuration.setText(String.valueOf(workout.getDuration()));
//
//                    // Установка изображения группы мышц
//                    String muscleGroup = determineMuscleGroup(workout.getSuggestedWorkout());
//                    setMuscleImage(muscleGroup);
//                } else {
//                    finish();
//                }
//            }
//
//            @Override
//            public void onCancelled(DatabaseError error) {
//                finish();
//            }
//        });
//    }
//
//    private String determineMuscleGroup(String suggestedWorkout) {
//        if (suggestedWorkout.toLowerCase().contains("push-ups") || suggestedWorkout.toLowerCase().contains("bench press")) {
//            return "Chest";
//        } else if (suggestedWorkout.toLowerCase().contains("pull-ups") || suggestedWorkout.toLowerCase().contains("deadlifts")) {
//            return "Back";
//        } else if (suggestedWorkout.toLowerCase().contains("bicep curls") || suggestedWorkout.toLowerCase().contains("tricep dips")) {
//            return "Arms";
//        } else if (suggestedWorkout.toLowerCase().contains("squats") || suggestedWorkout.toLowerCase().contains("lunges")) {
//            return "Legs";
//        } else if (suggestedWorkout.toLowerCase().contains("plank") || suggestedWorkout.toLowerCase().contains("crunches")) {
//            return "Abs";
//        } else if (suggestedWorkout.toLowerCase().contains("shoulder press") || suggestedWorkout.toLowerCase().contains("lateral raises")) {
//            return "Shoulders";
//        } else {
//            return "Full Body";
//        }
//    }
//
//    private void setMuscleImage(String muscleGroup) {
//        switch (muscleGroup.toLowerCase()) {
//            case "chest":
//                muscleImage.setImageResource(R.drawable.ic_chest);
//                break;
//            case "back":
//                muscleImage.setImageResource(R.drawable.ic_back);
//                break;
//            case "arms":
//                muscleImage.setImageResource(R.drawable.ic_arms);
//                break;
//            case "legs":
//                muscleImage.setImageResource(R.drawable.ic_legs);
//                break;
//            case "abs":
//                muscleImage.setImageResource(R.drawable.ic_abs);
//                break;
//            case "shoulders":
//                muscleImage.setImageResource(R.drawable.ic_shoulders);
//                break;
//            default:
//                muscleImage.setImageResource(R.drawable.ic_default_workout);
//                break;
//        }
//    }
//}