package com.example.smartcoach;


import android.os.Bundle;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.example.smartcoach.models.AutoGeneratedWorkout;

public class WorkoutDetailActivity extends AppCompatActivity {
    public static final String EXTRA_WORKOUT = "extra_workout";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_workout_detail);

        AutoGeneratedWorkout workout = getIntent().getParcelableExtra(EXTRA_WORKOUT);
        if (workout == null) {
            finish();
            return;
        }

        ((TextView) findViewById(R.id.tvDetailDate)).setText(workout.getDate());
        ((TextView) findViewById(R.id.tvDetailGoal)).setText(workout.getWorkoutGoal());
        ((TextView) findViewById(R.id.tvDetailSuggested)).setText(workout.getSuggestedWorkout());
        ((TextView) findViewById(R.id.tvDetailIntensity)).setText(workout.getIntensityLevel());
        ((TextView) findViewById(R.id.tvDetailSets)).setText(String.valueOf(workout.getSets()));
        ((TextView) findViewById(R.id.tvDetailDuration)).setText(String.valueOf(workout.getDuration()));
    }
}
