package com.example.smartcoach.models;

import android.os.Parcel;
import android.os.Parcelable;

public class AutoGeneratedWorkout implements Parcelable {
    private String autoWorkoutID;
    private String userID;
    private String suggestedWorkout;
    private int duration;
    private String intensityLevel;
    private int sets;
    private String date;
    private String workoutGoal;

    // Конструктор по умолчанию для Firebase
    public AutoGeneratedWorkout() {}

    public AutoGeneratedWorkout(String autoWorkoutID, String userID, String suggestedWorkout, int duration,
                                String intensityLevel, int sets, String date, String workoutGoal) {
        this.autoWorkoutID = autoWorkoutID;
        this.userID = userID;
        this.suggestedWorkout = suggestedWorkout;
        this.duration = duration;
        this.intensityLevel = intensityLevel;
        this.sets = sets;
        this.date = date;
        this.workoutGoal = workoutGoal;
    }

    // Геттеры и сеттеры
    public String getAutoWorkoutID() { return autoWorkoutID; }
    public void setAutoWorkoutID(String autoWorkoutID) { this.autoWorkoutID = autoWorkoutID; }
    public String getUserID() { return userID; }
    public void setUserID(String userID) { this.userID = userID; }
    public String getSuggestedWorkout() { return suggestedWorkout; }
    public void setSuggestedWorkout(String suggestedWorkout) { this.suggestedWorkout = suggestedWorkout; }
    public int getDuration() { return duration; }
    public void setDuration(int duration) { this.duration = duration; }
    public String getIntensityLevel() { return intensityLevel; }
    public void setIntensityLevel(String intensityLevel) { this.intensityLevel = intensityLevel; }
    public int getSets() { return sets; }
    public void setSets(int sets) { this.sets = sets; }
    public String getDate() { return date; }
    public void setDate(String date) { this.date = date; }
    public String getWorkoutGoal() { return workoutGoal; }
    public void setWorkoutGoal(String workoutGoal) { this.workoutGoal = workoutGoal; }

    protected AutoGeneratedWorkout(Parcel in) {
        autoWorkoutID = in.readString();
        userID = in.readString();
        suggestedWorkout = in.readString();
        duration = in.readInt();
        intensityLevel = in.readString();
        sets = in.readInt();
        date = in.readString();
        workoutGoal = in.readString();
    }

    public static final Creator<AutoGeneratedWorkout> CREATOR = new Creator<AutoGeneratedWorkout>() {
        @Override
        public AutoGeneratedWorkout createFromParcel(Parcel in) {
            return new AutoGeneratedWorkout(in);
        }

        @Override
        public AutoGeneratedWorkout[] newArray(int size) {
            return new AutoGeneratedWorkout[size];
        }
    };

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(autoWorkoutID);
        dest.writeString(userID);
        dest.writeString(suggestedWorkout);
        dest.writeInt(duration);
        dest.writeString(intensityLevel);
        dest.writeInt(sets);
        dest.writeString(date);
        dest.writeString(workoutGoal);
    }

    @Override
    public int describeContents() {
        return 0;
    }
}
